---
- name:            Ensure os-osvms tasks are performed for osvms_users
  include_tasks:
    file:          osvms.yml
    apply:
      become:      true
      become_user: "{{ user }}"
  loop:            "{{ osvms_users }}"
  loop_control:
    loop_var:      user
